### ISSUE TITLE
Program crashes when save is opened?

### ISSUE THREAD

**Issue by JediBiscuit** [robertnunn/DRG-Save-Editor#1]
When i try to open the save file the program becomes unresponsive and freezes requiring windows to close the program, i have tried running in adminstrator mode and using the back up saves in the folder but have had no luck sadly.

**Comment by robertnunn** [comment]
I just pushed a new version that should fix the issue. Please let me know if you still have the freezing problem.

**Comment by JediBiscuit** [comment]
I've downloaded the new file but now the save editor wont open at all, UAC pops up asking to allow it, the two command windows appear then close, tried running in admin mode again dosent seem to be working. Using Windows 10 if that matters?

**Comment by robertnunn** [comment]
Can you upload a screen shot of the error? Including the command prompt window that might have debug information on it? You can add "pause" to the end of the "start editor.cmd" file to prevent it from autoclosing.

**Comment by JediBiscuit** [comment]
Added pause to the end but the window still closes. No error codes just opens two command menus, one shows the location of the file then they both close at the same time, no errors at all unsure why it wont open now the last version did.

**Comment by robertnunn** [comment]
It shouldn't be opening two command windows, just the one. When you say "location of the file" which file are you referring to? The game save or one of the editor files (e.g., editor.ui)?

**Comment by JediBiscuit** [comment]
![start editor](https://user-images.githubusercontent.com/76931428/103568524-96c1c980-4ebd-11eb-949b-380e8ee9a957.png)
 
When i start with the DRG Save editor application set to admin mode whilst using the start editor command it creates two windows, ive turned admin mode off and tried with the start editor button and just received this command window before closing itself.

**Comment by robertnunn** [comment]
You shouldn't need the run as an administrator, but I haven't used windows 10. Does the editor UI appear? If so, are the text boxes and menu items responsive?

**Comment by JediBiscuit** [comment]
The command windows just close and dont open the editor, the editor opened before you updated it not sure why is not doing it this time?

**Comment by JediBiscuit** [comment]
I ran the application in windows 7 mode and got this error before it quickly closed.
![error](https://user-images.githubusercontent.com/76931428/103569456-36cc2280-4ebf-11eb-966c-7090e8406413.png)

**Comment by robertnunn** [comment]
Please replace the .ui file with this one and that should fix that particular error.
[editor ui.zip](https://github.com/robertnunn/DRG-Save-Editor/files/5766361/editor.ui.zip)

**Comment by JediBiscuit** [comment]
![stuck](https://user-images.githubusercontent.com/76931428/103577054-02129800-4ecc-11eb-9ae1-5e65f36f17af.png)

The editor now opens but still gets stuck trying to load the file for some reason :(

**Comment by robertnunn** [comment]
Usually that means there's an error in parsing the save file, could you upload a copy of your save file so I can see what's going wrong?

**Comment by JediBiscuit** [comment]
[Save.zip](https://github.com/robertnunn/DRG-Save-Editor/files/5766695/Save.zip)
There the save file, good luck bro i really hope this works :')

**Comment by robertnunn** [comment]
Ok, so a quick look tells me that you probably haven't forged any overclocks yet. Is this the case?

**Comment by JediBiscuit** [comment]
No i havent its a new save, bad ram corrupted one of my drives so had to start fresh a while ago. Guesssing i need to craft one first to make it work?

**Comment by robertnunn** [comment]
Most likely you just need to forge one overclock (any, even cosmetic) and it should work. I'll definitely fix this bug in the next release.

**Comment by JediBiscuit** [comment]
Got the file to load, added the over clocks i wanted but upon loading into the game it starts asif it is a fresh install. Not sure why this is, seems to wipe the save. We are getting closer though.

**Comment by JediBiscuit** [comment]
Even mineral values cause the game to load as a clean save not sure how this is happening.

**Comment by robertnunn** [comment]
So to confirm, you loaded your working save, forged an overclock, exited the game, opened the save with the editor, changed mineral values, loaded the save, and progress was reset?

**Comment by JediBiscuit** [comment]
Yes, i tried to over clock first but it reset then tried the second time with just minerals and it reset again. The file is loading just an issue saving it, wipes the save for some reason.

**Comment by robertnunn** [comment]
I just tested this myself, and it's resetting my save as well. I'll post again when I fix it.

**Comment by robertnunn** [comment]
OK! I think I've solved the saving issue. There was a subtle but very big mistake I made when saving the file that resulted in the save being truncated to a few hundred bytes. I just tested the compiled version (1.3.2) on my own save and things worked on my end. Please try the new version and let me know if it works.

**Comment by JediBiscuit** [comment]
Will try now.

**Comment by JediBiscuit** [comment]
You've done it, works perfectly. Well done :')

**Comment by robertnunn** [comment]
F@$&ing finally! Glad it's working for you, ROCK AND STONE!

**Comment by JediBiscuit** [comment]
ROCK AND STONE FOREVER!

**Comment by JediBiscuit** [comment]
But really job well done, i wouldnt know where to start on making a save editor, thank you for the help.
